# Generated by Django 3.0 on 2020-01-22 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_type', models.CharField(choices=[('CHECKING ACCOUNT', 'CHECKING ACCOUNT'), ('SAVINGS ACCOUNT', 'SAVINGS ACCOUNT'), ('CREDIT CARD ACCOUNT', 'CREDIT CARD ACCOUNT')], default='CHECKING ACCOUNT', max_length=20)),
                ('balance', models.IntegerField(default=0)),
            ],
        ),
    ]
