# Generated by Django 3.0 on 2020-01-22 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MoneyAccounts',
            new_name='MoneyAccount',
        ),
    ]
