# Generated by Django 3.0 on 2020-01-26 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0002_auto_20200122_1242'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='automatic_payment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_accounts', to='data_tracking.MoneyAccount'),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_name',
            field=models.CharField(default='Expense', max_length=10),
        ),
        migrations.AddField(
            model_name='bill',
            name='bill_type',
            field=models.CharField(choices=[('WEEKLY EXPENSE', 'WEEKLY EXPENSE'), ('BI-WEEKLY EXPENSE', 'BI-WEEKLY EXPENSE'), ('MONTHLY EXPENSE', 'MONTHLY EXPSENSE'), ('ONE TIME EXPENSE', 'ONE TIME EXPENSE')], default='ONE TIME EXPENSE', max_length=20),
        ),
    ]
