# Generated by Django 3.0 on 2020-02-25 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0006_auto_20200202_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='automatic_payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personal_accounts', to='data_tracking.MoneyAccount'),
        ),
    ]
