# Generated by Django 3.0 on 2020-02-25 22:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_tracking', '0009_auto_20200225_1728'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MonthlyBill',
        ),
    ]
